wrappers_Home_Work
dimon22510/TAF_AQA18_onl pull request #8
Opened 2023-01-15 20:29 UTC by dimon22510

2023-01-16 17:48 UTC, wildpioneer requested changes

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +    public void selectByIndex(int index) {
Не понимаю суть этого метода? Что мы хотим выбрать по индексу в чекбоксе?

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +    public void selectByValue(String value) {
Аналогично с selectByIndex

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +    public void selectByText(String text) {
Аналогично с selectByIndex

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/CheckBox.java
> +        for (WebElement webElement : driver.findElements(By.name(attributeNameValue))) {
Чекбокс всегда существует в единственном варианте

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +        for (WebElement webElement : driver.findElements(By.className(allListDropDown))){
Сам Dropdown существует в единственном варианте, а вот его значения - во множественном

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +    public void selectionByIndexDropDownMenuElement(int index) {
Исходя из названия - это метод для выбора DropDown-а по Index - но мы работаем с определенным DropDown. А вот его значения можно выбрать по индексу

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +    public void selectionLiIdElement(boolean condition) {
Выбор Li ID - не понимаю, что ты выбираешь и по чем?
Li  по ID, но я что такое LI?

Скорее всего это должен быть вариант selectOptionByID? - так понятнее вроде

2023-01-16 17:48 UTC, wildpioneer commented on src/test/java/elements/DropDownMenu.java
> +    public void clickLiIdElement() {
мне как пользователю кликать в DropDown ни к чему - а вот select (выбрать) - другое дело
а если это технический метод в помощь другим - тогда он не должен быт public

2023-01-17 17:34 UTC, dimon22510 commented on src/test/java/elements/CheckBox.java
> +    public void selectByIndex(int index) {
Та же суть как и с radioButton что мы делали с вами на занятии, то есть я так же нашёл по name и закинул в массив, выполнял поиск элемента по индексу, value, тексту и делал клик.

2023-01-18 17:33 UTC, closed without merging